name = "lmpify_badge"
main = "README.ts"
compatibility_date = "2025-05-21"


routes = [
  { pattern = "badge.lmpify.com", custom_domain = true },
  { pattern = "b.lmpify.com", custom_domain = true }
]
[dev]
port = 3000
